import { generateTransactionReference } from '@/app/lib/utils';
import { 
  Role, 
  DocumentType, 
  KycStatus, 
  NotificationType, 
  TwoFactorMethod, 
  TransactionType, 
  TransactionStatus, 
  PaymentMethod,  
  InvestmentStatus, 
  ReferralStatus, 
  AlertLevel, 
  Gender,
  WalletType
} from '@prisma/client';

// Date helper
const daysAgo = (days: number): Date => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

// Countries data
export const countries = [
  {
    id: BigInt(1),
    name: 'Cameroun',
    country_code: 'CM',
    dial_code: '+237',
  },
  {
    id: BigInt(2),
    name: 'Gabon',
    country_code: 'GA',
    dial_code: '+241',
  },
  {
    id: BigInt(3),
    name: 'RCA',
    country_code: 'CF',
    dial_code: '+236',
  },
  {
    id: BigInt(4),
    name: 'Tchad',
    country_code: 'TD',
    dial_code: '+235',
  },
  {
    id: BigInt(5),
    name: 'Benin',
    country_code: 'BJ',
    dial_code: '+229',
  },
  {
    id: BigInt(6),
    name: 'Côte d\'Ivoire',
    country_code: 'CI',
    dial_code: '+225',
  },
  {
    id: BigInt(7),
    name: 'Nigeria',
    country_code: 'NG',
    dial_code: '+234',
  },
];

// Users data
export const users = [
  {
    id: BigInt(1),
    email: 'admin@juatradx.com',
    password_hash: '123456789',
    first_name: 'Admin',
    last_name: 'System',
    role: Role.ADMIN,
    is_email_verified: true,
    email_verified_at: new Date(),
    referral_code: 'ADMINJUATRADX',
    is_active: true,
    country_id: BigInt(1),
  },
  {
    id: BigInt(2),
    email: 'jean.dupont@example.com',
    password_hash: '123456789',
    first_name: 'Jua',
    last_name: 'Tradx',
    phone: '+237690123456',
    role: Role.USER,
    is_email_verified: true,
    email_verified_at: new Date(),
    referral_code: 'JUATRADX',
    is_active: true,
    referred_by: BigInt(1),
    country_id: BigInt(1),
  },
  // {
  //   id: BigInt(3),
  //   email: 'marie.ekotto@example.com',
  //   password_hash: '123456789',
  //   first_name: 'Marie',
  //   last_name: 'Ekotto',
  //   phone: '+237677987654',
  //   role: Role.USER,
  //   is_email_verified: false,
  //   referral_code: 'MARIEK2',
  //   is_active: true,
  //   referred_by: BigInt(2),
  //   country_id: BigInt(1),
  // },
  // {
  //   id: BigInt(4),
  //   email: 'paul.gale@example.com',
  //   password_hash: '123456789',
  //   first_name: 'Paul',
  //   last_name: 'Gale',
  //   phone: '+237699876543',
  //   role: Role.USER,
  //   is_email_verified: true,
  //   email_verified_at: new Date(),
  //   referral_code: 'PAULGAL3',
  //   is_active: false,
  //   referred_by: BigInt(2),
  //   country_id: BigInt(2),
  // },
  // {
  //   id: BigInt(5),
  //   email: 'amina.oke@example.com',
  //   password_hash: '123456789',
  //   first_name: 'Amina',
  //   last_name: 'Oke',
  //   phone: '+2348031234567',
  //   role: Role.USER,
  //   is_email_verified: true,
  //   email_verified_at: new Date(),
  //   referral_code: 'AMINAOK4',
  //   is_active: true,
  //   referred_by: BigInt(3),
  //   country_id: BigInt(7),
  // },
  // {
  //   id: BigInt(6),
  //   email: 'francois.ndiaye@example.com',
  //   password_hash: '123456789',
  //   first_name: 'Francois',
  //   last_name: 'Ndiaye',
  //   phone: '+2250701234567',
  //   role: Role.USER,
  //   is_email_verified: false,
  //   referral_code: 'FRANNDI5',
  //   is_active: true,
  //   referred_by: BigInt(3),
  //   country_id: BigInt(6),
  // },
];

// User profiles
// export const userProfiles = [
//   {
//     user_id: BigInt(1),
//     address: 'Rue de l’Administration, Yaoundé',
//     city: 'Yaoundé',
//     postal_code: 'BP 1000',
//     date_of_birth: new Date('1975-01-01'),
//     gender: Gender.Homme,
//     avatar_url: 'https://example.com/avatars/admin.jpg',
//     timezone: 'Africa/Douala',
//     preferred_language: 'fr',
//   },
//   {
//     user_id: BigInt(2),
//     address: 'Quartier Bastos, Yaoundé',
//     city: 'Yaoundé',
//     postal_code: 'BP 2000',
//     date_of_birth: new Date('1990-05-15'),
//     gender: Gender.Homme,
//     avatar_url: 'https://example.com/avatars/jean.jpg',
//     timezone: 'Africa/Douala',
//     preferred_language: 'fr',
//   },
//   // {
//   //   user_id: BigInt(3),
//   //   address: 'Bonapriso, Douala',
//   //   city: 'Douala',
//   //   postal_code: 'BP 3000',
//   //   date_of_birth: new Date('1988-11-20'),
//   //   gender: Gender.Femme,
//   //   avatar_url: 'https://example.com/avatars/marie.jpg',
//   //   timezone: 'Africa/Douala',
//   //   preferred_language: 'fr',
//   // },
//   // {
//   //   user_id: BigInt(4),
//   //   address: 'Mvan, Yaoundé',
//   //   city: 'Yaoundé',
//   //   postal_code: 'BP 4000',
//   //   date_of_birth: new Date('1980-03-10'),
//   //   gender: Gender.Homme,
//   //   avatar_url: 'https://example.com/avatars/paul.jpg',
//   //   timezone: 'Africa/Libreville',
//   //   preferred_language: 'fr',
//   // },
//   // {
//   //   user_id: BigInt(5),
//   //   address: 'Victoria Island, Lagos',
//   //   city: 'Lagos',
//   //   postal_code: '101241',
//   //   date_of_birth: new Date('1992-07-22'),
//   //   gender: Gender.Femme,
//   //   avatar_url: 'https://example.com/avatars/amina.jpg',
//   //   timezone: 'Africa/Lagos',
//   //   preferred_language: 'en',
//   // },
//   // {
//   //   user_id: BigInt(6),
//   //   address: 'Treichville, Abidjan',
//   //   city: 'Abidjan',
//   //   postal_code: 'BP 5000',
//   //   date_of_birth: new Date('1985-09-10'),
//   //   gender: Gender.Homme,
//   //   avatar_url: 'https://example.com/avatars/francois.jpg',
//   //   timezone: 'Africa/Abidjan',
//   //   preferred_language: 'fr',
//   // },
// ];

// User security
// export const userSecurities = [
//   {
//     user_id: BigInt(1),
//     two_factor_enabled: true,
//     two_factor_method: TwoFactorMethod.AUTHENTICATOR,
//     two_factor_secret: 'ABCDEFGHIJKLMNOP',
//     backup_codes: '123456,789012,345678',
//     password_changed_at: new Date(),
//   },
//   {
//     user_id: BigInt(2),
//     two_factor_enabled: false,
//     password_changed_at: new Date(),
//   },
//   {
//     user_id: BigInt(3),
//     two_factor_enabled: true,
//     two_factor_method: TwoFactorMethod.SMS,
//     two_factor_secret: 'XYZ123456789',
//     backup_codes: '987654,321098',
//     password_changed_at: new Date(),
//   },
//   {
//     user_id: BigInt(4),
//     two_factor_enabled: false,
//     password_changed_at: new Date(),
//   },
//   {
//     user_id: BigInt(5),
//     two_factor_enabled: true,
//     two_factor_method: TwoFactorMethod.EMAIL,
//     two_factor_secret: 'PQRSTUVWXYZ123',
//     backup_codes: '456789,012345',
//     password_changed_at: new Date(),
//   },
//   {
//     user_id: BigInt(6),
//     two_factor_enabled: false,
//     password_changed_at: new Date(),
//   },
// ];

// Wallets
// export const wallets = [
//   {
//     id: BigInt(1),
//     user_id: BigInt(1),
//     balance: 0,
//     locked_balance: 0.00,
//     type: WalletType.DEPOSIT,
//   },
//   {
//     id: BigInt(2),
//     user_id: BigInt(1),
//     balance: 450.00,
//     locked_balance: 0.00,
//     type: WalletType.PROFIT,
//   },
//   {
//     id: BigInt(3),
//     user_id: BigInt(1),
//     balance: 0.00,
//     locked_balance: 20.00,
//     type: WalletType.BONUS,
//   },
//    {
//     id: BigInt(4),
//     user_id: BigInt(2),
//     balance: 0,
//     locked_balance: 0.00,
//     type: WalletType.DEPOSIT,
//   },
//   {
//     id: BigInt(5),
//     user_id: BigInt(2),
//     balance: 0.00,
//     locked_balance: 0.00,
//     type: WalletType.PROFIT,
//   },
//   {
//     id: BigInt(6),
//     user_id: BigInt(2),
//     balance: 0.00,
//     locked_balance: 20.00,
//     type: WalletType.BONUS,
//   },  
  
//   {
//     id: BigInt(7),
//     user_id: BigInt(3),
//     balance: 0,
//     locked_balance: 0.00,
//     type: WalletType.DEPOSIT,
//   },
//   {
//     id: BigInt(8),
//     user_id: BigInt(3),
//     balance: 0.00,
//     locked_balance: 0.00,
//     type: WalletType.PROFIT,
//   },
//   {
//     id: BigInt(9),
//     user_id: BigInt(3),
//     balance: 0.00,
//     locked_balance: 0.00,
//     type: WalletType.BONUS,
//   },
  
//   {
//     id: BigInt(10),
//     user_id: BigInt(4),
//     balance: 0,
//     locked_balance: 0.00,
//     type: WalletType.DEPOSIT,
//   },
//   {
//     id: BigInt(11),
//     user_id: BigInt(4),
//     balance: 0.00,
//     locked_balance: 0.00,
//     type: WalletType.PROFIT,
//   },
//   {
//     id: BigInt(12),
//     user_id: BigInt(4),
//     balance: 0.00,
//     locked_balance: 0.00,
//     type: WalletType.BONUS,
//   },
// ];

// Payment accounts
// export const paymentAccounts = [
//   {
//     id: BigInt(1),
//     user_id: BigInt(2),
//     type: PaymentMethod.MOBILE,
//     account_identifier: '+237690123456',
//     provider: 'Orange Money',
//     is_default: true,
//   },
//   {
//     id: BigInt(2),
//     user_id: BigInt(2),
//     type: PaymentMethod.BITCOIN,
//     account_identifier: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
//     provider: 'Bitcoin',
//     is_default: false,
//   },
//   {
//     id: BigInt(3),
//     user_id: BigInt(3),
//     type: PaymentMethod.MOBILE,
//     account_identifier: '+237677987654',
//     provider: 'MTN Money',
//     is_default: true,
//   },
//   {
//     id: BigInt(4),
//     user_id: BigInt(3),
//     type: PaymentMethod.ETHEREUM,
//     account_identifier: '0x1234567890abcdef1234567890abcdef12345678',
//     provider: 'Ethereum',
//     is_default: false,
//   },
//   {
//     id: BigInt(5),
//     user_id: BigInt(4),
//     type: PaymentMethod.MOBILE,
//     account_identifier: '+237699876543',
//     provider: 'Orange Money',
//     is_default: true,
//   },
//   {
//     id: BigInt(6),
//     user_id: BigInt(4),
//     type: PaymentMethod.ETHEREUM,
//     account_identifier: '0xabcdef1234567890abcdef1234567890abcdef12',
//     provider: 'Ethereum',
//     is_default: false,
//   },
//   {
//     id: BigInt(7),
//     user_id: BigInt(5),
//     type: PaymentMethod.MOBILE,
//     account_identifier: '+2348031234567',
//     provider: 'MTN Money',
//     is_default: true,
//   },
//   {
//     id: BigInt(8),
//     user_id: BigInt(5),
//     type: PaymentMethod.USDT,
//     account_identifier: '0x9876543210abcdef1234567890abcdef12345678',
//     provider: 'USDT',
//     is_default: false,
//   },
//   {
//     id: BigInt(9),
//     user_id: BigInt(6),
//     type: PaymentMethod.MOBILE,
//     account_identifier: '+2250701234567',
//     provider: 'Moov Money',
//     is_default: true,
//   },
// ];

// Investment plans
export const investmentPlans = [
  {
    id: BigInt(1),
    name: 'Plan Découverte',
    description: 'Idéal pour débuter',
    min_amount: 25.00,
    max_amount: 199.99,
    daily_profit_percent: 5,
    duration_days: 30,
    is_active: true,
    withdrawal_lock_days: 15,
    capital_return: true,
    featured: false,
  },
  {
    id: BigInt(2),
    name: 'Plan Croissance',
    description: 'Le plus populaire',
    min_amount: 200,
    max_amount: 999.99,
    daily_profit_percent: 7.5,
    duration_days: 25,
    is_active: true,
    withdrawal_lock_days: 10,
    capital_return: true,
    featured: true,
  },
  {
    id: BigInt(3),
    name: 'Plan Élite',
    description: 'Pour une croissance maximale',
    min_amount: 1000,
    daily_profit_percent: 10,
    duration_days: 20,
    is_active: true,
    withdrawal_lock_days: 7,
    capital_return: true,
    featured: false,
  },
  {
    id: BigInt(4),
    name: 'Plan Ultimate',
    description: 'Pour les institutions',
    min_amount: 5000,
    daily_profit_percent: 12.5,
    duration_days: 15,
    is_active: true,
    withdrawal_lock_days: 7,
    capital_return: true,
    featured: false,
  },
];

// Transactions
// export const transactions = [
//   {
//     id: BigInt(1),
//     user_id: BigInt(2),
//     wallet_id: BigInt(3),
//     payment_account_id: BigInt(1),
//     txid: 'TX10001',
//     type: TransactionType.DEPOSIT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DEPOSIT),
//     details: 'Dépôt initial via Orange Money',
//     processed_at: daysAgo(45),
//   },
//   {
//     id: BigInt(2),
//     user_id: BigInt(2),
//     wallet_id: BigInt(3),
//     payment_account_id: BigInt(2),
//     txid: 'TX10002',
//     type: TransactionType.DEPOSIT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DEPOSIT),
//     wallet_address: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
//     details: 'Dépôt Bitcoin',
//     processed_at: daysAgo(40),
//   },
//   {
//     id: BigInt(3),
//     user_id: BigInt(2),
//     wallet_id: BigInt(3),
//     txid: 'TX10003',
//     type: TransactionType.INVESTMENT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.INVESTMENT),
//     details: 'Investissement dans Plan Basique',
//     processed_at: daysAgo(35),
//   },
//   {
//     id: BigInt(4),
//     user_id: BigInt(3),
//     wallet_id: BigInt(5),
//     payment_account_id: BigInt(3),
//     txid: 'TX10004',
//     type: TransactionType.DEPOSIT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DEPOSIT),
//     details: 'Dépôt initial via MTN Money',
//     processed_at: daysAgo(30),
//   },
//   {
//     id: BigInt(5),
//     user_id: BigInt(3),
//     wallet_id: BigInt(5),
//     payment_account_id: BigInt(4),
//     txid: 'TX10005',
//     type: TransactionType.DEPOSIT,
//     status: TransactionStatus.PENDING,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DEPOSIT),
//     wallet_address: '0x1234567890abcdef1234567890abcdef12345678',
//     details: 'Dépôt Ethereum en attente',
//     processed_at: null,
//   },
//   {
//     id: BigInt(6),
//     user_id: BigInt(3),
//     wallet_id: BigInt(5),
//     txid: 'TX10006',
//     type: TransactionType.INVESTMENT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.INVESTMENT),
//     details: 'Investissement dans Plan Basique',
//     processed_at: daysAgo(20),
//   },
//   {
//     id: BigInt(7),
//     user_id: BigInt(2),
//     wallet_id: BigInt(4),
//     txid: 'TX10007',
//     type: TransactionType.DIVIDEND,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DIVIDEND),
//     details: 'Profit quotidien Plan Basique',
//     processed_at: daysAgo(1),
//   },
//   {
//     id: BigInt(8),
//     user_id: BigInt(2),
//     wallet_id: BigInt(4),
//     payment_account_id: BigInt(1),
//     txid: 'TX10008',
//     type: TransactionType.WITHDRAWAL,
//     status: TransactionStatus.PENDING,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.WITHDRAWAL),
//     details: 'Demande de retrait Orange Money',
//     processed_at: null,
//   },
//   {
//     id: BigInt(9),
//     user_id: BigInt(4),
//     wallet_id: BigInt(7),
//     payment_account_id: BigInt(5),
//     txid: 'TX10009',
//     type: TransactionType.DEPOSIT,
//     status: TransactionStatus.FAILED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DEPOSIT),
//     details: 'Dépôt échoué Orange Money',
//     processed_at: daysAgo(10),
//   },
//   {
//     id: BigInt(10),
//     user_id: BigInt(2),
//     wallet_id: BigInt(4),
//     payment_account_id: BigInt(2),
//     txid: 'TX10010',
//     type: TransactionType.WITHDRAWAL,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.WITHDRAWAL),
//     wallet_address: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
//     details: 'Retrait Bitcoin',
//     processed_at: daysAgo(1),
//   },
//   {
//     id: BigInt(11),
//     user_id: BigInt(4),
//     wallet_id: BigInt(7),
//     txid: 'TX10011',
//     type: TransactionType.INVESTMENT,
//     status: TransactionStatus.CANCELLED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.INVESTMENT),
//     details: 'Investissement annulé dans Plan Avancé',
//     processed_at: daysAgo(15),
//   },
//   {
//     id: BigInt(12),
//     user_id: BigInt(5),
//     wallet_id: BigInt(9),
//     payment_account_id: BigInt(7),
//     txid: 'TX10012',
//     type: TransactionType.DEPOSIT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DEPOSIT),
//     details: 'Dépôt via MTN Money',
//     processed_at: daysAgo(25),
//   },
//   {
//     id: BigInt(13),
//     user_id: BigInt(5),
//     wallet_id: BigInt(9),
//     txid: 'TX10013',
//     type: TransactionType.INVESTMENT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.INVESTMENT),
//     details: 'Investissement dans Plan Avancé',
//     processed_at: daysAgo(20),
//   },
//   {
//     id: BigInt(14),
//     user_id: BigInt(6),
//     wallet_id: BigInt(11),
//     payment_account_id: BigInt(9),
//     txid: 'TX10014',
//     type: TransactionType.DEPOSIT,
//     status: TransactionStatus.COMPLETED,
//     amount: 850.00,
//     fee: 0.00,
//     reference: generateTransactionReference(TransactionType.DEPOSIT),
//     details: 'Dépôt via Moov Money',
//     processed_at: daysAgo(15),
//   },
// ];

// // Investments
// export const investments = [
//   {
//     id: BigInt(1),
//     user_id: BigInt(2),
//     plan_id: BigInt(1),
//     transaction_id: BigInt(3),
//     amount: 500.00,
//     expected_profit: 725000.00,
//     profit_earned: 225000.00,
//     start_date: daysAgo(35),
//     end_date: daysAgo(5),
//     status: InvestmentStatus.COMPLETED,
//   },
//   {
//     id: BigInt(2),
//     user_id: BigInt(3),
//     plan_id: BigInt(1),
//     transaction_id: BigInt(6),
//     amount: 500000.00,
//     expected_profit: 725000.00,
//     profit_earned: 45000.00,
//     start_date: daysAgo(20),
//     end_date: daysAgo(-10),
//     status: InvestmentStatus.ACTIVE,
//   },
//   {
//     id: BigInt(3),
//     user_id: BigInt(4),
//     plan_id: BigInt(2),
//     transaction_id: BigInt(11),
//     amount: 600000.00,
//     expected_profit: 960000.00,
//     profit_earned: 0.00,
//     start_date: daysAgo(15),
//     end_date: daysAgo(-45),
//     status: InvestmentStatus.CANCELLED,
//   },
//   {
//     id: BigInt(4),
//     user_id: BigInt(5),
//     plan_id: BigInt(2),
//     transaction_id: BigInt(13),
//     amount: 1500000.00,
//     expected_profit: 2400000.00,
//     profit_earned: 300000.00,
//     start_date: daysAgo(20),
//     end_date: daysAgo(-40),
//     status: InvestmentStatus.ACTIVE,
//   },
// ];

// Investment profits

// export const investmentProfits = [
//   {
//     id: BigInt(1),
//     investment_id: BigInt(1),
//     transaction_id: BigInt(7),
//     amount: 7500.00,
//     profit_date: daysAgo(1),
//     is_compounded: false,
//   },
//   {
//     id: BigInt(2),
//     investment_id: BigInt(2),
//     transaction_id: BigInt(6),
//     amount: 7500.00,
//     profit_date: daysAgo(2),
//     is_compounded: true,
//   },
//   {
//     id: BigInt(3),
//     investment_id: BigInt(4),
//     transaction_id: BigInt(13),
//     amount: 30000.00,
//     profit_date: daysAgo(1),
//     is_compounded: false,
//   },
// ];

// KYC verifications
// export const kycVerifications = [
//   {
//     id: BigInt(1),
//     user_id: BigInt(2),
//     document_type: DocumentType.ID_CARD,
//     document_number: 'CM12345678',
//     document_front_url: 'https://example.com/documents/jean_front.jpg',
//     document_back_url: 'https://example.com/documents/jean_back.jpg',
//     selfie_url: 'https://example.com/documents/jean_selfie.jpg',
//     status: KycStatus.APPROVED,
//     reviewed_by: BigInt(1),
//     reviewed_at: daysAgo(38),
//   },
//   {
//     id: BigInt(2),
//     user_id: BigInt(3),
//     document_type: DocumentType.PASSPORT,
//     document_number: 'CM98765432',
//     document_front_url: 'https://example.com/documents/marie_passport.jpg',
//     selfie_url: 'https://example.com/documents/marie_selfie.jpg',
//     status: KycStatus.PENDING,
//   },
//   {
//     id: BigInt(3),
//     user_id: BigInt(4),
//     document_type: DocumentType.ID_CARD,
//     document_number: 'CM45678912',
//     document_front_url: 'https://example.com/documents/paul_front.jpg',
//     document_back_url: 'https://example.com/documents/paul_back.jpg',
//     selfie_url: 'https://example.com/documents/paul_selfie.jpg',
//     status: KycStatus.REJECTED,
//     rejection_reason: 'Document flou',
//     reviewed_by: BigInt(1),
//     reviewed_at: daysAgo(12),
//   },
//   {
//     id: BigInt(4),
//     user_id: BigInt(5),
//     document_type: DocumentType.PASSPORT,
//     document_number: 'NG12345678',
//     document_front_url: 'https://example.com/documents/amina_passport.jpg',
//     selfie_url: 'https://example.com/documents/amina_selfie.jpg',
//     status: KycStatus.APPROVED,
//     reviewed_by: BigInt(1),
//     reviewed_at: daysAgo(20),
//   },
//   {
//     id: BigInt(5),
//     user_id: BigInt(6),
//     document_type: DocumentType.DRIVER_LICENSE,
//     document_number: 'CI98765432',
//     document_front_url: 'https://example.com/documents/francois_license.jpg',
//     document_back_url: 'https://example.com/documents/francois_license_back.jpg',
//     selfie_url: 'https://example.com/documents/francois_selfie.jpg',
//     status: KycStatus.PENDING,
//   },
// ];



// Referrals
// export const referrals = [
//   {
//     id: BigInt(1),
//     referred_by: BigInt(1),
//     user_id: BigInt(3),
//     earnings: 0.0,
//     status: ReferralStatus.REWARDED,
//     signed_up_at: daysAgo(50),
//     first_deposit_at: daysAgo(45),
//   },
 
//   {
//     id: BigInt(2),
//     referred_by: BigInt(2),
//     user_id: BigInt(3),
//     earnings: 0.00,
//     status: ReferralStatus.PENDING,
//     signed_up_at: daysAgo(20),
//   },
//   {
//     id: BigInt(3),
//     referred_by: BigInt(2),
//     user_id: BigInt(4),
//     earnings: 10.00,
//     status: ReferralStatus.REWARDED,
//     signed_up_at: daysAgo(25),
//     first_deposit_at: daysAgo(25),
//   },
//   {
//     id: BigInt(4),
//     referred_by: BigInt(3),
//     user_id: BigInt(5),
//     earnings: 30.00,
//     status: ReferralStatus.PENDING,
//     signed_up_at: daysAgo(15),
//   },
//   {
//     id: BigInt(5),
//     referred_by: BigInt(3),
//     user_id: BigInt(6),
//     earnings: 20.00,
//     status: ReferralStatus.PENDING,
//     signed_up_at: daysAgo(15),
//   },
// ];

// Referral bonuses
// export const referralBonuses = [
//   {
//     id: BigInt(1),
//     referral_id: BigInt(1),
//     transaction_id: BigInt(1),
//     amount: 0.00,
//     description: 'Bonus de parrainage pour Jean Dupont',
//   },
//   {
//     id: BigInt(2),
//     referral_id: BigInt(2),
//     transaction_id: BigInt(4),
//     amount: 0.00,
//     description: 'Bonus de parrainage pour Marie Ekotto',
//   },
//   {
//     id: BigInt(3),
//     referral_id: BigInt(4),
//     transaction_id: BigInt(12),
//     amount: 40000.00,
//     description: 'Bonus de parrainage pour Amina Oke',
//   },
// ];

// Withdrawals
// export const withdrawals = [
//   {
//     id: BigInt(1),
//     transaction_id: BigInt(8),
//     user_id: BigInt(2),
//     payment_account_id: BigInt(1),
//     approved_by: null,
//     approved_at: null,
//   },
//   {
//     id: BigInt(2),
//     transaction_id: BigInt(10),
//     user_id: BigInt(2),
//     payment_account_id: BigInt(2),
//     approved_by: BigInt(1),
//     approved_at: daysAgo(1),
//   },
//   {
//     id: BigInt(3),
//     transaction_id: BigInt(9),
//     user_id: BigInt(4),
//     payment_account_id: BigInt(5),
//     rejection_reason: 'KYC non approuvé',
//     approved_by: null,
//     approved_at: null,
//   },
// ];

// Notifications
// export const notifications = [
//   {
//     id: BigInt(1),
//     user_id: BigInt(2),
//     title: 'Dépôt Reçu',
//     message: 'Votre dépôt de 1 000 000 $ via Orange Money a été crédité.',
//     type: NotificationType.TRANSACTION,
//     is_read: true,
//     read_at: daysAgo(44),
//     metadata: { amount: 1000000, provider: 'Orange Money' },
//   },
//   {
//     id: BigInt(2),
//     user_id: BigInt(2),
//     title: 'KYC Approuvé',
//     message: 'Votre vérification d’identité a été approuvée.',
//     type: NotificationType.KYC,
//     is_read: true,
//     read_at: daysAgo(37),
//   },
//   {
//     id: BigInt(3),
//     user_id: BigInt(3),
//     title: 'Bienvenue sur Juatradx',
//     message: 'Merci de vous être inscrit sur Juatradx.',
//     type: NotificationType.SYSTEM,
//     is_read: false,
//   },
//   {
//     id: BigInt(4),
//     user_id: BigInt(4),
//     title: 'KYC Rejeté',
//     message: 'Votre vérification KYC a été rejetée : document flou.',
//     type: NotificationType.KYC,
//     is_read: false,
//   },
//   {
//     id: BigInt(5),
//     user_id: BigInt(2),
//     title: 'Retrait en Attente',
//     message: 'Votre demande de retrait de 200 000 $ via Orange Money est en attente.',
//     type: NotificationType.TRANSACTION,
//     is_read: false,
//     metadata: { amount: 200000, provider: 'Orange Money' },
//   },
//   {
//     id: BigInt(6),
//     user_id: BigInt(5),
//     title: 'Dépôt Reçu',
//     message: 'Votre dépôt de 2 000 000 NGN via MTN Money a été crédité.',
//     type: NotificationType.TRANSACTION,
//     is_read: true,
//     read_at: daysAgo(24),
//     metadata: { amount: 2000000, provider: 'MTN Money' },
//   },
//   {
//     id: BigInt(7),
//     user_id: BigInt(5),
//     title: 'KYC Approuvé',
//     message: 'Votre vérification d’identité a été approuvée.',
//     type: NotificationType.KYC,
//     is_read: true,
//     read_at: daysAgo(19),
//   },
//   {
//     id: BigInt(8),
//     user_id: BigInt(6),
//     title: 'Bienvenue sur Juatradx',
//     message: 'Merci de vous être inscrit sur Juatradx.',
//     type: NotificationType.SYSTEM,
//     is_read: false,
//   },
// ];

// System settings
export const systemSettings = [
  {
    id: BigInt(1),
    key: 'referral_bonus_percentage',
    value: '10',
    description: 'Pourcentage de bonus pour parrainage',
  },
  {
    id: BigInt(2),
    key: 'minimum_deposit',
    value: '25',
    description: 'Montant minimum de dépôt en $',
  },
  {
    id: BigInt(3),
    key: 'default_currency',
    value: '$',
    description: 'Devise par défaut pour les portefeuilles',
  },
  {
    id: BigInt(4),
    key: 'maintenance_mode',
    value: 'false',
    description: 'Statut de maintenance du système',
  },
  {
    id: BigInt(5),
    key: 'registration_bonus_percentage',
    value: '10',
    description: 'Bonus du parrain lors de l\'inscription d\'un fileul',
  },
  {
    id: BigInt(6),
    key: 'first_deposit_bonus_percentage',
    value: '20',
    description: 'Bonus premier dépot',
  },
  {
    id: BigInt(7),
    key: 'Default_refferal_code',
    value: 'JUATRADX',
    description: 'Bonus premier dépot',
  },
  
];

// System alerts
export const systemAlerts = [
  {
    id: BigInt(1),
    title: 'Maintenance Planifiée',
    message: 'Maintenance prévue le 15 août de 2h00 à 4h00 (WAT).',
    level: AlertLevel.INFO,
    start_date: daysAgo(5),
    end_date: daysAgo(-2),
    is_active: false,
  },
  {
    id: BigInt(2),
    title: 'Nouveau Plan d’Investissement',
    message: 'Découvrez notre nouveau Plan Premium avec des rendements élevés !',
    level: AlertLevel.SUCCESS,
    start_date: daysAgo(2),
    is_active: true,
  },
  {
    id: BigInt(3),
    title: 'Attention : Tentative de Fraude',
    message: 'Vérifiez vos comptes de paiement pour éviter les fraudes.',
    level: AlertLevel.WARNING,
    start_date: daysAgo(1),
    is_active: true,
  },
];

// Admin activities
// export const adminActivities = [
//   {
//     id: BigInt(1),
//     user_id: BigInt(1),
//     action: 'APPROVED_KYC',
//     ip_address: '192.168.1.1',
//     user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
//     metadata: { userId: '2', kycId: '1' },
//     created_at: daysAgo(38),
//   },
//   {
//     id: BigInt(2),
//     user_id: BigInt(1),
//     action: 'APPROVED_WITHDRAWAL',
//     ip_address: '192.168.1.1',
//     user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
//     metadata: { withdrawalId: '2', amount: '7500.00' },
//     created_at: daysAgo(1),
//   },
//   {
//     id: BigInt(3),
//     user_id: BigInt(1),
//     action: 'REJECTED_KYC',
//     ip_address: '192.168.1.1',
//     user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
//     metadata: { userId: '4', kycId: '3', reason: 'Document flou' },
//     created_at: daysAgo(12),
//   },
//   {
//     id: BigInt(4),
//     user_id: BigInt(1),
//     action: 'APPROVED_KYC',
//     ip_address: '192.168.1.1',
//     user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
//     metadata: { userId: '5', kycId: '4' },
//     created_at: daysAgo(20),
//   },
// ];